#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Dec 30 23:51:56 2018

@author: aaron
"""


import os
import shutil

def check_dir(path):
    if not os.path.exists(path):
        os.mkdir(path)
        
        
def task_rename_files(path1, path2):
    
    temp = os.listdir(path1)
    
    for i in range(len(temp)):
        ori_full_path = os.path.join(path1, 'img_'+str(i)+'.pkl')
        
        new_full_path = os.path.join(path2, 'img_'+str(i+20000)+'.pkl')
        
        shutil.copy(ori_full_path, new_full_path)
        
        
        
        
        
        
if __name__ == '__main__':
        
    path = '/hdisk/Ubuntu/backup/aWS/obj-detection/Mask_RCNN-master/samples/coco/rmac/feats_db_miniset/feats'
    
    new_path = '/hdisk/Ubuntu/backup/aWS/obj-detection/Mask_RCNN-master/samples/coco/rmac/feats_db_miniset/feats_rename'
    check_dir(new_path)
    task_rename_files(path, new_path)

